spin_manifest_version = 2

[application]
name = "cloud-life"
version = "0.1.0"
authors = ["deadprogram <ron@hybridgroup.com>"]
description = ""

[[trigger.http]]
route = "/start-universe"
component = "start-universe"

[component.start-universe]
source = "start-universe/main.wasm"
allowed_outbound_hosts = []
[component.start-universe.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "start-universe"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/run-universe"
component = "run-universe"

[component.run-universe]
source = "run-universe/main.wasm"
allowed_outbound_hosts = []
[component.run-universe.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "run-universe"
watch = ["**/*.go", "go.mod"]
