spin_manifest_version = 2

[application]
name = "cloud-life"
version = "0.1.0"
authors = ["deadprogram <ron@hybridgroup.com>"]
description = ""

[[trigger.http]]
route = "/universe/..."
component = "universe"

[component.universe]
source = "universe/main.wasm"
key_value_stores = ["default"]
allowed_outbound_hosts = []
[component.universe.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "universe"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/multiverse/..."
component = "multiverse"

[component.multiverse]
source = "multiverse/main.wasm"
allowed_outbound_hosts = []
[component.multiverse.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "multiverse"
watch = ["**/*.go", "go.mod"]
